# Generated by Django 5.1.7 on 2025-03-16 23:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0002_startup_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='startups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='startup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),  # Исправление
        ),
    ]
