# Generated by Django 5.1.7 on 2025-03-31 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profession',
            field=models.CharField(blank=True, choices=[('backend', 'Backend-разработчик'), ('frontend', 'Frontend-разработчик'), ('fullstack', 'Fullstack-разработчик'), ('uiux', 'Дизайнер UI/UX'), ('pm', 'Менеджер продукта'), ('marketing', 'Маркетолог'), ('copywriter', 'Копирайтер'), ('data_analyst', 'Аналитик данных'), ('devops', 'Инженер DevOps'), ('qa', 'Тестировщик QA'), ('ba', 'Бизнес-аналитик'), ('project_manager', 'Проджект-менеджер'), ('finance', 'Финансист'), ('hr', 'HR-специалист')], max_length=50, null=True),
        ),
    ]
