# Generated by Django 5.2 on 2025-06-01 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskfile',
            options={'ordering': ['is_folder', 'name']},
        ),
        migrations.AddField(
            model_name='taskfile',
            name='is_folder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskfile',
            name='parent_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tasks.taskfile'),
        ),
        migrations.AddField(
            model_name='taskfile',
            name='path',
            field=models.CharField(default='/', max_length=255),
        ),
        migrations.AlterField(
            model_name='taskfile',
            name='content_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='taskfile',
            name='size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='taskfile',
            unique_together={('task', 'parent_folder', 'name')},
        ),
    ]
