# Generated by Django 5.2 on 2025-06-01 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_taskfile_options_taskfile_is_folder_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskactivity',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='taskactivity',
            name='action',
            field=models.CharField(choices=[('created', 'Создание'), ('completed', 'Завершение'), ('reopened', 'Возобновление'), ('edited', 'Редактирование'), ('commented', 'Комментарий'), ('created_subtask', 'Создание подзадачи'), ('edited_subtask', 'Редактирование подзадачи'), ('deleted_subtask', 'Удаление подзадачи'), ('completed_subtask', 'Завершение подзадачи'), ('reopened_subtask', 'Возобновление подзадачи')], max_length=20),
        ),
        migrations.AlterField(
            model_name='taskactivity',
            name='subtask',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='tasks.subtask'),
        ),
        migrations.DeleteModel(
            name='TaskFile',
        ),
    ]
