# Generated by Django 5.1.7 on 2025-04-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_subtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
