# Generated by Django 5.1.7 on 2025-04-16 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_subtask_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskactivity',
            name='subtask',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='tasks.subtask'),
        ),
    ]
