# Generated by Django 5.1.7 on 2025-04-16 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_taskactivity_subtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskactivity',
            name='action',
            field=models.CharField(choices=[('created', 'Создание'), ('completed', 'Завершение'), ('reopened', 'Возобновление'), ('edited', 'Редактирование'), ('commented', 'Комментарий'), ('created_subtask', 'Создание подзадачи'), ('completed_subtask', 'Завершение подзадачи'), ('reopened_subtask', 'Возобновление подзадачи')], max_length=20),
        ),
    ]
