# Generated by Django 5.1.7 on 2025-04-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_taskactivity_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
