# Generated by Django 5.1.7 on 2025-04-17 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_subtask_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammembership',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
