# Generated by Django 5.1.7 on 2025-04-21 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_tag_task_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
