# Generated by Django 5.1.7 on 2025-04-22 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_remove_task_tags_delete_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('in_progress', 'В процессе'), ('done', 'Готово')], default='pending', max_length=20),
        ),
    ]
