# Generated by Django 5.1.7 on 2025-04-22 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_team_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='status',
        ),
    ]
