# Generated by Django 5.1.7 on 2025-04-23 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_task_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
    ]
